name: clash-sudoku
version: 0.1.0
category: hardware
license: MIT

extra-source-files:
  - README.md

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc

  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib ^>= 0.1.2
  - barbies
  - barbies-th

  - clash-shake >= 0.3.0 && < 0.5.0

  - lens
  - mtl
  - arrows
  - clash-protocols
  - clash-cores

  - hedgehog
  - deepseq

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver
  -Wunused-imports

source-dirs:
  - src

executables:
  sudoku:
    main: simulator.hs
