resolver: clash-1.8.1.yaml

packages:
  - '.'

  - clash-protocols/clash-protocols-base
  - clash-protocols/clash-protocols

extra-deps:
  - clash-shake-0.3.2

  - git: https://github.com/cchalmers/circuit-notation.git
    commit: 19b386c4aa3ff690758ae089c7754303f3500cc9
